/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private final String defaultGreeting = "Hello world (default)";

    private String greeting;

    public String getGreeting() {
        return greeting != null ? greeting : defaultGreeting;
    }

    public void setGreeting(String greeting) {
        this.greeting = greeting;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
