/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Frank' at '7/20/16 9:48 PM' with Gradle 2.14
 *
 * @author Frank, @date 7/20/16 9:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
