CREATE TABLE IF NOT EXISTS ACCOUNT_DETAILS (
	CUSTOMER_NAME VARCHAR(60) NOT NULL,
	ACCOUNT_NAME VARCHAR(60) NOT NULL,
	ACCOUNT_NUMBER INTEGER NOT NULL,
	BALANCE DECIMAL(20,2),
	PRIMARY KEY (ACCOUNT_NUMBER));
	
DELETE FROM ACCOUNT_DETAILS;
INSERT INTO ACCOUNT_DETAILS ("FRANK BROWN", "MAIN CHECKING", 100298000, 2000.43);
INSERT INTO ACCOUNT_DETAILS ("CHARLIE BROWN", "UUUUUGGGGHHH CHECKING", 10021001, 1.08);