/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Frank' at '2/24/18 8:57 AM' with Gradle 2.14
 *
 * @author Frank, @date 2/24/18 8:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
